<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mc_googlesitemap"
 *
 * Auto generated by Extension Builder 2017-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google Sitemap for Pages and Contents',
	'description' => 'Please use this as a plugin in pages instead of content element [Upgraded version of mc_googlesitemap]',
	'category' => 'plugin',
	'author' => 'HOJA.M.A',
	'author_email' => 'hoja.ma@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.14',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
