-- #
-- # Table structure for table 'tt_content'
-- #
-- CREATE TABLE tt_content (
-- 	tx_pitsgooglesitemap_objective tinytext NOT NULL,
-- 	tx_pitsgooglesitemap_lastmod int(11) unsigned DEFAULT '0' NOT NULL,
-- 	tx_pitsgooglesitemap_pageuid blob NOT NULL,
-- 	tx_pitsgooglesitemap_url text NOT NULL,
-- 	tx_pitsgooglesitemap_changefreq int(11) unsigned DEFAULT '0' NOT NULL,
-- 	tx_pitsgooglesitemap_priority double DEFAULT '0' NOT NULL
-- );
-- 
-- 
-- 
-- #
-- # Table structure for table 'pages'
-- #
-- CREATE TABLE pages (
-- 	tx_pitsgooglesitemap_priority double DEFAULT '0' NOT NULL,
-- 	tx_pitsgooglesitemap_changefreq int(11) unsigned DEFAULT '0' NOT NULL
-- );
-- 
-- 
